# Generated by Django 2.2 on 2020-03-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_auto_20200312_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_ref',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
